# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: "/#home"         # Weâ€™ll define an id for the top section
    weight: 10
  - name: Research Interests
    url: "/#research"     # anchor to Research section
    weight: 20
  - name: Publications
    url: "/#publications"
    weight: 30
  - name: Projects
    url: "/#projects"
    weight: 40
  - name: Teaching
    url: "/#teaching"
    weight: 50
  - name: Invited Talks
    url: "/#talks"
    weight: 60
  - name: Awards
    url: "/#awards"
    weight: 70
  - name: CV
    url: "uploads/cv.pdf"
    weight: 80
