[build]
  # We manually download Hugo 0.120.4 because Netlify keeps forcing 0.148.1
  command = "curl -L https://github.com/gohugoio/hugo/releases/download/v0.120.4/hugo_extended_0.120.4_linux-amd64.tar.gz -o hugo.tar.gz && tar -zxvf hugo.tar.gz hugo && ./hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
